### ISSUE TITLE
Button Click

### ISSUE THREAD

**Issue by redowl3** [SQL-MisterMagoo/Blazor.PWA.MSBuild#19]
I've just taken the latest version to test and have used the default Blazor server side project to convert to a PWA.  After deploying (via Azure), I can't get the counter button click event to work? Menu items work fine, is there something additional I need to do?

Thanks

**Comment by Lil3p** [comment]
I am facing the same problem. 
On my local machine the app works perfectly once I deploy to azure click events stop working the pages  will render but you can't click any buttons. On  the same app if you remove the PWA package everything works perfectly on my local and on azure. I suspect the problem is caused by the catching service killing the Signal R connection

**Comment by redowl3** [comment]
Enabling websockets in Azure resolved the issue for me.

**Comment by SQL-MisterMagoo** [comment]
Thanks @redowl3 for helping out!

@Lil3p in case you are not sure how, you enable websockets on the azure portal like this

![image](https://user-images.githubusercontent.com/11338430/74321417-20cee400-4d7a-11ea-8449-4178f71aa1a1.png)

**Comment by Lil3p** [comment]
Yes that was the issue my app was running inside a VM so I installed websockets in IIS and everything is now working as expected. I'm not sure why when I removed the Blazor.PWA.MSBuild nuget package it worked, I would think it is supposed to fail even without the PWA package. That said thanks a lot for the help @redowl3  and @SQL-MisterMagoo

**Comment by SQL-MisterMagoo** [comment]
The problem is with the ServiceWorker without websockets, which is why removing it "fixes" things. But as you really want Websockets enabled, it's not something I plan to do anything about.

thanks for reporting back!
